### ISSUE TITLE
User output

### ISSUE THREAD

**Issue by leebaird** [ezra-buckingham/terry-the-terraformer#39]
Suggest the following simple output to the user once a successful build has completed.

<IP> <type> <cloud provider>  <domain> for each server

Example:
1.1.1.1   https   aws   evil-corp.com
1.1.1.2  https   aws   nothing-here.com
1.1.1.3  team   do

**Comment by ezra-buckingham** [comment]
This now will output in a table format... cheers!

**Comment by ezra-buckingham** [comment]
Example: ```Server Resources:

╒═══════════════╤════════════════╤═════════════╤══════════════╤══════════╕
│ server_name   │ public_ip      │ nebula_ip   │ provider     │ domain   │
╞═══════════════╪════════════════╪═════════════╪══════════════╪══════════╡
│ testing       │ 142.93.181.184 │ 10.53.53.1  │ digitalocean │          │
├───────────────┼────────────────┼─────────────┼──────────────┼──────────┤
│ strict-slour  │ 18.221.124.213 │ 10.53.53.2  │ aws          │          │
╘═══════════════╧════════════════╧═════════════╧══════════════╧══════════╛

Domain Resources:

╒══════════╤════════╤═══════════════╤═════════╕
│ domain   │ host   │ record_type   │ value   │
╞══════════╪════════╪═══════════════╪═════════╡
╘══════════╧════════╧═══════════════╧═════════╛```
