### ISSUE TITLE
AWS security groups

### ISSUE THREAD

**Issue by leebaird** [ezra-buckingham/terry-the-terraformer#4]
Using the -r switch with 'destroy' should delete all AWS security groups that were created.

Each AWS instance that is deployed has an attached security group.
These security groups all have the same rule: allow traffic on all ports and protocols. This seems redundant.

**Comment by ezra-buckingham** [comment]
I would love to see what you are seeing, I am seeing deletion of groups. Can you provide more information please? It should be created in your default VPC and that might be causing issues...

**Comment by leebaird** [comment]
This seems to be working now.
