### ISSUE TITLE
wiki examples missing command

### ISSUE THREAD

**Issue by tecknicaltom** [ezra-buckingham/terry-the-terraformer#46]
The first examples (both short-hand and fully-qualified forms) on https://github.com/ezra-buckingham/terry-the-terraformer/wiki/Usage-Examples for using the create command are missing the create command.

**Comment by ezra-buckingham** [comment]
Yep, the wiki needs to be updated since my big refactor IIRC

**Comment by ezra-buckingham** [comment]
Done
