### ISSUE TITLE
Allow for multiple IPs and/or CIDRs in config.yml

### ISSUE THREAD

**Issue by leebaird** [ezra-buckingham/terry-the-terraformer#9]
Allow for multiple IPs and/or CIDRs for public_ip in config.yml

**Comment by ezra-buckingham** [comment]
After migrating to more builtin functionality, passing in a CIDR should be possible. As far as multiple IPs, that would require some heavy refactoring of ansible. Not a change I have on the roadmap just yet... You can add another entry to `default_users` to add additional IP ranges, you just need to create "arbitrary" user accounts
